#!/usr/bin/env python

"""Command Line Tool"""

from sound_downloader.arguments_parser import get_arguments
from sound_downloader.downloader import YoutubeAudioDownloader


def main():
    args = get_arguments()
    path_file = args.path_file
    path_to_save = args.path_to_save
    downloader = YoutubeAudioDownloader(path_file, path_to_save=path_to_save)
    downloader.download_audios()


if __name__ == "__main__":
    main()